language: python
notifications:
  email: false
sudo: true
#python:
#  - 2.7
#  - 3.4
#  - 3.5
#  - 3.6 
matrix:
  include:
    - python: 2.7
      dist: trusty
      sudo: required
      virtualenv:
        system_site_packages: false
      addons:
        apt:
          packages:
            - python-numpy
            - python-scipy
before_script:
 - export PYTHONPATH=$PYTHONPATH:/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages
install:
 - sudo python pystrain/setup.py install
 - pip install -r test/requirements.txt

script:
 - bin/StrainTensor.py -i data/CNRS_midas.vel
 
after_script: cd ~
