language: python
notifications:
  email: false
#sudo: true
python:
#  - "2.7"
#  - "3.4"
#  - "3.5"
#  - "3.6"      # current default Python on Travis CI
#  - "3.7"
#  - "3.8"
#  - "3.9"
#  - "3.9-dev"  # 3.9 development branch
#  - "nightly"  # nightly build

matrix:
  include:
    - python: 2.7
      dist: trusty
     #sudo: required
      virtualenv:
        system_site_packages: true
      addons:
        apt:
          packages:
            - python-numpy
            - python-scipy


before_script:
# - export PYTHONPATH=$PYTHONPATH:/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages
 - export PYTHONPATH=$PYTHONPATH:$(pwd)
 - export PYTHONPATH=$PYTHONPATH:$(pwd)/pystrain
 
install:
 - python pystrain/setup.py install
# - pip install -r test/requirements.txt

script:
 - bin/StrainTensor.py --help
 #- bin/StrainTensor.py -i data/CNRS_midas.vel -r=18/30/34/43 -c
 
# after_script: cd ~
