sudo: required
dist: xenial
language: python

python:
  - "2.7"

install:
 - pip install -r tests/requirements.txt
 - python pystrain/setup.py install
script:
 - bin/StrainTensor.py -i data/CNRS_midas.vel
 
after_script: cd ~
