sudo: required
dist: xenial
language: python

python:
  - "2.7"

before_install:
 - sudo apt-get install -qq python-numpy python-scipy
install:
 - python pystrain/setup.py install
script:
 - bin/StrainTensor.py
 
after_script: cd ~
