language: python
notifications:
  email: false
sudo: false
#python:
#  - 2.7
#  - pypy
#  - 3.4
#  - 3.5
#  - 3.6 
#  - pypy3
matrix:
  include:
    - python: 2.7
      dist: trusty
      sudo: required
      virtualenv:
        system_site_packages: true
      addons:
        apt:
          packages:
            - python-numpy
            - python-scipy
before_script:
 - export PYTHONPATH=$PYTHONPATH:/home/travis/.local/lib/python2.7/site-packages/
install:
 - python pystrain/setup.py install
 - pip install -r test/requirements.txt

script:
 - bin/StrainTensor.py -i data/CNRS_midas.vel
 
after_script: cd ~
