#!/bin/bash
#use this file to cheange default parameters for plots
# //////////////////////////////////////////////////////////////////////////////

#Path to input file directory
pth2inptf=../bin/


#outfiles
outfile=output.ps

#colormaps
landcpt=land_man.cpt
bathcpt=bath_man.cpt


# //////////////////////////////////////////////////////////////////////////////
# Set default REGION 
west=17 #19.5
east=30 #29
south=34
north=43 #42
projscale=6000000
frame=1

# length of plot scale (Km)
sclength=100

logo_pos="BL/.1c/.1c/StrainTool"

# scale position parameters for velocities
vsclon=22.34
vsclat=37.68
vscmagn=20
VSC=0.05

STRSC=.0080
ROTSC=.7
strsclon=20.4
strsclat=36.3
