#!/bin/bash
#use this file to cheange default parameters for plots
# //////////////////////////////////////////////////////////////////////////////
# Set PATHS parameters
pth2dems=${HOME}/Map_project/dems
# inputTopoL=${pth2dems}/ETOPO1_Bed_g_gmt4.grd
# inputTopoB=${pth2dems}/ETOPO1_Bed_g_gmt4.grd
inputTopoL=${pth2dems}/ETOPO1_gr_resample01m.grd   #ETOPO1_Bed_g_gmt4.grd
inputTopoB=${pth2dems}/ETOPO1_gr_resample01m.grd    #ETOPO1_Bed_g_gmt4.grd
pth2logos=$HOME/Map_project/logos/DSOlogo2.eps
pth2faults=$HOME/Map_project/faults/NOAFaults_v1.0.gmt

#Path to input file directory
# pth2inptf=$(pwd)
pth2inptf=../


#outfiles
outfile=output.ps
# out_jpg=output.jpg
#colormaps
landcpt=land_man.cpt
bathcpt=bath_man.cpt


# //////////////////////////////////////////////////////////////////////////////
# Set default REGION for GREECE
# west=19
# east=30.6
# south=33
# north=42
# projscale=6000000
# frame=2
# 
# 
# logo_pos="BL/6c/-1.5c/GeoTool[a]DSO"
# logo_pos2="-C16c/15.6c"
# legendc="-Jx1i -R0/8/0/8 -Dx18.5c/12.6c/3.6c/3.5c/BL"	
# maptitle=""

# # ////////////////////////////////////////////////////////////////
# # scale position parameters for velocities
# vsclon=20.2
# vsclat=34
# vscmagn=20
# VSC=0.05
# 
# STRSC=50
# ROTSC=1
# strsclon=20.2
# strsclat=34.1

# # # //////////////////////////////////////////////////////////////////////////////
# # # Set default REGION for IONIO - PATRA extended to kerkyra
# west=19.5
# east=22.7
# south=36.85
# north=40
# projscale=1900000
# frame=1
# # gmt	gmtset PS_MEDIA 26cx22c
# scale="-Lf19.9/37/36:24/50+l+jr"
# logo_pos="BL/6c/-1.5c/DSO[at]ntua"
# logo_pos2="-C15.6c/15.9c"
# legendc="-Jx1i -R0/8/0/8 -Dx18.5c/12.6c/3.6c/3.5c/BL"	
# 
# # scale position parameters for velocities
# vsclon=19.7
# vsclat=37.1
# vscmagn=20
# VSC=0.05
# 
# STRSC=50
# ROTSC=1
# strsclon=19.9
# strsclat=37.2



# //////////////////////////////////////////////////////////////////////////////
# Set default REGION for ONLY PATRA
west=19.5
east=29
south=34
north=42
projscale=5000000
frame=1
# gmt	gmtset PS_MEDIA 26cx22c
scale="-Lf22.4/37.6/36:24/30+l+jr"

logo_pos="BL/.1c/.1c/DSO[at]ntua"
logo_pos2="-C15.6c/15.9c"
legendc="-Jx1i -R0/8/0/8 -Dx18.5c/12.6c/3.6c/3.5c/BL"	
# 

# scale position parameters for velocities
vsclon=22.34
vsclat=37.68
vscmagn=20
VSC=0.05

STRSC=.0050
ROTSC=.7
strsclon=20.4
strsclat=36.3

# #//////////////////// me TRIGONA!!!!!
# Set default REGION for ONLY PATRA
# west=20.2
# east=22.7
# south=37.5
# south=36.92
# north=39.02
# projscale=1300000
# frame=1
# gmt	gmtset PS_MEDIA 26cx22c
# scale="-Lf22.4/37/36:24/30+l+jr"
# 
# logo_pos="BL/6c/-1.5c/DSO[at]ntua"
# logo_pos2="-C15.6c/15.9c"
# legendc="-Jx1i -R0/8/0/8 -Dx18.5c/12.6c/3.6c/3.5c/BL"	
# 
# 
# scale position parameters for velocities
# vsclon=22.34
# vsclat=37.38
# vscmagn=20
# VSC=0.05
# 
# STRSC=50
# ROTSC=1
# strsclon=22.40
# strsclat=37.3
# 
